const languages = {
    en : {
        mainHeader : "WATCH VIDEOS AND EARN MONEY",
        cta : "This is the time to make money on your mobile phones and laptops Being anywhere in Ethiopia.",
        getStarted : "Get Started",
        dashboard : "Dashboard",
        threeSteps : "Three simple steps to get started.",
        register : "Register",
        watchVideo : "Watch Video",
        earn : "Earn",
        aboutUs : "About Us",
        contactUs : "Contact Us",
        aboutOne : "Mina play is the first Ethiopian website and application where you can make money by watching YouTube videos.",
        aboutTwo : "A variety of videos are included to satisfy your needs, such as educational content , entertainment, news, books, different programs and shows. Points and Rewards Mina play will be given based on how long you watch the videos",
        aboutThree : "Each video will have a maximum of 1 point. When you watch the full video you get 1 point, if you watch half you get 0.5 and so on. You should aim for the maximum point possible before submitting your point. After submission you will not be able to earn more money from that video.",
        aboutFour : "At the end of each month, members get paid or collect their Dembulos. The minimum withdrawal rate on mina play starts at 100 Birr.",
        howMinaWorks : "How does Mina play work?",
        step : "Step",
        stepOne : "Open Mina Play",
        stepOneDetail : "Log in to the website, check out the home page, and you will find an icon for registration. Then click the register button on the home page.",
        stepTwo : "Create an Account",
        stepTwoDetail : "Complete the personal information in the Sign-up form. Create a password and submit. Once your account is created login and confirm your email address. Then refresh your browser.",
        stepThree : "Pay Registration Fee",
        stepThreeDetail : "Select and transfer or pay the registration fee via the listed money transferring methods. Then click confirm the payment button.",
        stepFour : "Confirm Payment",
        stepFourDetail : "Fill in the requested questions and confirm your payment.",
        stepFive : "You're Done",
        stepFiveDetail : "Now you can Sign-in to mina play. Get instant access to work from your comfort and earn money.",
        q1 : "What is Mina play?",
        a1 : "Mina play is the first Ethiopian website and application where you can earn money by watching YouTube videos.",
        q2 : "How does Mina play work?",
        a2 : "After completing the registration process, you get a membership, which allows you to access the videos. Once you register, you have a personal code to access your account.",
        q3 : "Is Mina play legit?",
        a3 : "Mina play is a legit website and application which you do as a side hustle.",
        q4 : "How to withdraw money?",
        a4 : "The collected coins or points from mina play can be converted into cash and can be withdrawn or transferred via telebirr.",
        faq : "Frequently Asked Questions",
        close : "Close",
        logout : "Logout", 
        login : "Login", 
        search : "Search",
        profile : "Profile",
        videos : "Videos",
        message : "Message",
        fullName : "Full Name",
        firstName : "First Name",
        lastName : "Last Name",
        email : "Email",
        phoneNumber : "Phone Number",
        password : "Password",
        oldPassword : "Old Password",
        newPassword : "New Password",
        confirmPassword : "Confirm Password",
        submit : "Submit",
        watchHistory : "Watch History",
        transactionHistory : "Transaction History",
        etb : "ETB",
        approved : "Approved",
        pending : "Pending",
        denied : "Denied",
        wallet : "Wallet",
        points : "Points",
        suggestedVideos : "Suggested Videos",
        withdraw : "Withdraw",
        pause : "Pause",
        play : "Play",
        pointAllocation : "Point Allocation",
        pap1 : "Minaplay users will be able to collect points depending on how soon they watch the videos after release.",
        pap2 : "Users that make more than 1,000 Birr will be charged with 35% service charge.",
        pap3 : "Users that make less than 500 Birr will be able to withdraw the points they made through Airtime.",
        pap4 : "When the first 6 months are up, users are required to register every 3 months.",
        duration : "Duration",
        minutes : "Minutes",
        birr : "Birr",
        month : "Month",
        hour : "Hour",
        day : "Day",
        week : "Week",
        currency : "Currency",
        amount : "Amount",
        supportUs : "Support Us",
        supportUsTxt : "If you like our work, send us a tip right from where you are.",
        warnSubmit : "After submitting your point, you won't be able to collect any more points from this video. Make sure you watched the whole video if you want to get the maximum point available.",
        waitPatiently : "After submitting, please wait patiently while we confirm your payment. It could take upto 2 days. Pay with chapa for immediate confirmation."
    },
    am : {
        mainHeader : "የኢንተርኔት አገልግሎት መጠቀምዎ ካልቀረ ተጨማሪ ገቢን ለምን አያገኙም? ",
        cta : "ቤትዎ ተቀምጠው በተንቀሳቃሽ ስልክዎ አልያም ላፕቶፕዎን በመጠቀም ገንዘብ የሚሰሩበት ጊዜ ደረሰ!",
        getStarted : "ይጀምሩ",
        dashboard : "መቆጣጠሪያ",
        threeSteps : "ለመጀመር 3 ቀላል ደረጃዎች",
        register : "ምዝገባ",
        watchVideo : "ተመልከት",
        earn : "አግኝ",
        aboutUs : "ስለ እኛ",
        contactUs : "ያግኙን",
        aboutOne : "ሚና ፕሌይ በኢትዮጵያ የመጀመሪያው የዪቲዮብ ቪዲዮዎችን በመመልከት ገንዘብ የሚሰሩበት (ክፍያ የሚያገኙበት) ዌብሳይት ነው።",
        aboutTwo : "ሚና ፕሌይን ከተቀላቀሉ በኋላ በዌብሳይቱ ላይ የሚያገኟቸውን የዩቲዩብ ቪዲዮዎችን በመመልከት ለአባላቱ ክፍያ የሚፈፅም ዌብሳይት ነው። ",
        aboutThree : "ሚና ፕሌይ ወጣቶች የኢንተርኔት መረብ አገልግሎትን እየተጠቀሙ እየተዝናኑ መረጃ እያገኙ እውቀት እየተካፈሉ ገንዘብ እንዲሰሩ የሚያስችል ዌብሳይትና ነው።",
        aboutFour : "በሚና ፕሌይ አዝናኝ፣ አስተማሪ፣ ቁምነገር አዘል ውይይቶች፣ አሳታፊ ፕሮግራሞች፣ ትረካዎች፣ መፅሐፍት እና ሌሎችም ቪዲዮዎች ማራኪ በሆነ አቀራረብና ደረጃውን በጠበቀ የቀረፃ ብቃት ተዘጋጅተው የሚቀርቡበት ዌብሳይት ነው።",
        howMinaWorks : "የሚና ፕሌይ ዌብሳይትን ለመጠቀም የመመዝገቢያ ሒደት",
        step : "ደረጃ",
        stepOne : "ሚና ፕሌይን ይክፈቱ",
        stepOneDetail : "www.minaplay.com በማለት ወደ ዌብሳይቱ ይግቡ; የመጀመሪያውን የመተዋወቂያ ገፅ ያገኛሉ።  Register (መመዝገቢያ) የሚል ምልክት ተቀምጧል። ምልክቱን ይጫኑ።",
        stepTwo : "አካውንት ይፍጠሩ",
        stepTwoDetail : "በገፁ ላይ በሚያገኙት የመመዝገቢያ ፎርም ላይ የሚጠየቁትን የግል መረጃዎች ይሙሉ። የይለፍ ቃል ያስገቡና ማረጋገጫ ይቀበሉ በማስከተልም ቀጣይ (Next) የሚለውን ቁልፍ ይጫኑ።",
        stepThree : "መመዝገቢያ",
        stepThreeDetail : "የተዘረዘሩትን የገንዘብ ማስተላለፊያ መንገዶች በመጠቀም የመመዝገቢያ ክፍያዎን ይፈፅሙ። በማስከተልም የማረጋገጫ ቁልፉን ይጫኑ።",
        stepFour : "መክፈልዎን ያረጋግጡ",
        stepFourDetail : "ክፍያ መፈፀምዎን የሚያረጋግጠውን መረጃ ይሙሉ።",
        stepFive : "ጨርሰዋል",
        stepFiveDetail : "አሁን የሚና ፕሌይ አባል ሆነዋል። ከዚህ በኋላ የከፈቱትን የግል አካውንትዎን እና የይለፍ ቃልዎን በመጠቀም በሚና ፕሌይ ላይ የሚያገኟቸውን ቪዲዮዎች በመመልከት ባሉበት ሆነው ገንዘብ ይስሩ፣ የሞባይል ጥቅል አገልግሎቶችን ያግኙ።",
        q1 : "ሚና ፕሌይ ምንድነው?",
        a1 : "ሚና ፕሌይ የዮቲዮብ ቪዲዮዎችን በመመልከት ክፍያ የሚያገኙበት ሜብሳይት ነው።",
        q2 : "ሚና ፕሌይ እንዴት ይሰራል?",
        a2 : "በሚና ፕሌይ ቪዲዮዎችን በመመልከት እና የተለያዩ ጥቅሞች (ተጨማሪ ገቢ) ለማግኘት የተመዘገቡ አባላት ወደ ዌብሳይቱ ገብተው ቪዲዮ ሲመለከቱ የሚያገኙትን ነጥብ በመቁጠር ወደ ክፍያ ቀይሮ አባላቱን ተጠቃሚ ያደርጋል። ",
        q3 : "ሚና ፕሌይ ህጋዊ ነው?",
        a3 : "ይህ ዌብሳይት ህጋዊ ሲሆን እንደአባላቱ አፈፃፀም እየተለካ ከሞባይል ጥቅሎች አንስቶ የገንዘብ ተከፋይ እስከመሆን የሚያደርሱ ጥቅማጥቅሞች የያዘ ዌብሳይት ነው።",
        q4 : "ክፍያን እንዴት መቀበል ይቻላል?",
        a4 : "አባላቱ ዌብሳይቱ ላይ እንደሰሩት መጠን በሞባይል ጥቅል አገልግሎቶች የሚያስገኝ ተግባርን ሲያከናውኑ በቀጥታ በስልካቸው የአየር ሰዓትና የኢንተርኔት ጥቅል አገልግሎቶች ይላኩላቸዋል። አባላቱ የስራቸው ክንውን የገንዘብ ተከፋይ ሲያደርጋቸው በቀጥታ በባንክ አካውንታቸው በኩል በየወሩ መጨረሻ ክፍያ ይፈፀምላቸዋል።",
        faq : "በተደጋጋሚ የተጠየቁ",
        close : "አጥፋ", 
        logout : "ዝጋ", 
        login : "ግባ",
        search : "ፈልግ",
        profile : "የኔ መረጃ",
        videos : "ቪድዮዎች",
        message : "መልዕክት",
        fullName : "ሙሉ ስም",
        firstName : "የመጀመሪያ ስም",
        lastName : "የወላጅ ስም",
        email : "ኢሜል",
        phoneNumber : "ስልክ ቁጥር",
        password : "የይለፍ ቃል",
        oldPassword : "የድሮ ይለፍ ቃል",
        newPassword : "አዲስ ይለፍ ቃል",
        confirmPassword : "አዲስ ይለፍ ቃል አረጋግጥ",
        submit : "አረጋግጥ",
        watchHistory : "የቀድሞ ምልከታዎች",
        transactionHistory : "የገንዘብ ዝውውሮች",
        etb : "ብር",
        approved : "የተረጋገጡ",
        pending : "ያልተወሰኑ",
        denied : "የተከለከሉ",
        wallet : "ዋሌት",
        points : "ነጥብ",
        suggestedVideos : "ተጨማሪ ቪድዮዎች",
        withdraw : "አውጣ",
        pause : "አቁም",
        play : "አጫውት",
        pointAllocation : "የክፍያ ሁኔታ",
        pap1 : "የሚና ፕሌይ አባላት የሚሰበስቡትን ነጥብ የሚወስነው ቪድዮው ከተለቀቀበት ሰዓት ጀምሮ እስከሚምለከቱበት ጊዜ ያለው እንደሚከተለው ተሰልቶ ነው። ",
        pap2 : "ከ1,000 ብር በላይ የሠራ ሰው 35% የአገልግሎት ክፍያ ይቆረጥበታል።",
        pap3 : "ከ500 ብር በታች የሠራ ሰው በብሩ መጠን የሞባይል ካርድ/ የአየር ሰዓት ክፍያ ይፈጸምለታል።",
        pap4 : "የመጀመሪያው ምዝገባ በተመዘገበ 6 ወር በኃላ በየ3 ወሩ ይታደሳል/ እንደ አዲስ ይመዘገባል።",
        duration : "እይታ",
        minutes : "ደቂቃ",
        birr : "ብር",
        month : "ወር",
        hour : "ሰዓት",
        day : "ቀን",
        week : "ሳምንት",
        currency: "መገበያያ",
        amount : "መጠን",
        supportUs : "ልታግዙን ለምትፈልጉ",
        supportUsTxt : "ይህንን ዌብሳይት እና ስራችንን ወዳችሁ በገንዘብ ማገዝ ለምትፈልጉ ከታች ባለው ቅጽ ካሉበት ሆነው ማገዝ ይችላሉ።",
        warnSubmit : "ነጥባችሁን ካስገባችሁ በኋላ ከዚህ ቪድዮ ተጨማሪ ነጥብ መሰብሰብ አይቻልም። ከዚህ ቪድዮ ማግኘት የምትችሉትን ሙሉ ነጥብ ለማግኘት ሙሉ ቪድዮውን ማየታችሁን ያረጋግጡ።",
        waitPatiently : "በባንክ የከፈላችሁበትን ማስረጃ ለማረጋገጥ እስከ 2 ቀን ሊፈጅ ስለሚችል በትዕግስት ይጠብቁን። ወድያውኑ እንዲረጋገጥላችሁ በቻፓ የክፍያ መንገድ ይጠቀሙ።"
    }
}

module.exports.languages = languages;